export const MINIMAL_ETH_STAKED = 1
export const MINIMAL_AVERAGE_PERCENTAGE_VALIDATORS_ONLINE = 66
export const SMALLER_PROBABILITY = 0
export const BIGGEST_PROBABILITY = 100
export const NET_REWARDS_COLOUR = '#3794FC'
export const PENALTIES_COLOUR = '#FF0000'
export const REWARDS_COLOUR = '#9D60FB'
